### ISSUE TITLE
publish the point cloud of the lidar in its own frame

### ISSUE THREAD

**Issue by bj108** [fsstudio-team/ZeroSimROSUnity#16]
Hi there, could it be possible to publish the point cloud of the lidar in its own frame (i.e. lidar_link) not the base_link frame? If yes, could you instruct the steps to set it up, please? Thank you.

**Comment by micahpearlman** [comment]
Apologies, I'm not sure I'm following the question.  You can set the "Parent Transform Id" to whatever you wish in the `ZOROSPointCloud2Publisher`  component.
