### ISSUE TITLE
How to rename/remap topics?

### ISSUE THREAD

**Issue by angelr31** [fsstudio-team/ZeroSimROSUnity#18]
I was wondering how one would go about remapping data from ZeroSim Nodes in Unity to different topics? i.e remapping depth topic in ZeroSim from /depth_registered/image_rect -> /camera_sim/example_name. Any help would be greatly appreciated

**Comment by anqitongxue** [comment]
这里是氨气同学的QQ邮箱，您的邮件我已收到，祝生活愉快~

**Comment by micahpearlman** [comment]
The `ZOROSDepthImagePublisher` contains a section called `ROS Topics`.  See attached image:
![ros_topics](https://user-images.githubusercontent.com/126005/151237823-97091762-3383-4cb1-a561-3fd5253e4a1d.png)
