### ISSUE TITLE
Running in ROS2

### ISSUE THREAD

**Issue by bj108** [fsstudio-team/ZeroSimROSUnity#19]
Hi there, is there a tutorial available for showing how to run the package in ROS2. The ROS2 rosbridge_server does not have a launch file to start up the tcp node (https://github.com/RobotWebTools/rosbridge_suite/tree/ros2/rosbridge_server/launch), which is different from ROS1 rosbridge_server (https://github.com/RobotWebTools/rosbridge_suite/tree/ros1/rosbridge_server/launch). Thank you!

**Comment by micahpearlman** [comment]
@bj108 Unfortunately we have not had direct experience using ROS2 as most of our users are still very active with ROS1.  That being said some users have reported success with having ZeroSim work in ROS2 environment but were not specific.  I would try https://github.com/ros2/ros1_bridge 

If you do find success would you mind reporting back on how it was done as it would be useful for other users.  

We do plan on supporting WebSockets at some point in the future (which then should allow ROS Bridge to work).
