### ISSUE TITLE
save point cloud data

### ISSUE THREAD

**Issue by yumianhuli2** [fsstudio-team/ZeroSimROSUnity#23]
Hello！
How to save the point cloud data in the simulation process?

Thank U！

**Comment by micahpearlman** [comment]
I'm not sure I understand the question?  I would imagine using ROS bags?

**Comment by micahpearlman** [comment]
Has this issue been resolved?

**Comment by yumianhuli2** [comment]
> Has this issue been resolved?

yeah，this is a solution.
