### ISSUE TITLE
Unable to import package 

### ISSUE THREAD

**Issue by vbelkina** [fsstudio-team/ZeroSimROSUnity#28]
Hello, I am trying to follow the tutorial to set this up, however, I keep getting the "Error adding package: git@github.com:fsstudio-team/ZeroSimROSUnity.git"
![image](https://user-images.githubusercontent.com/72238100/173137846-913c5d56-7d40-4b2f-83e7-55f097b7be87.png)

I am running on Ubuntu 20.04. I tried a couple of versions of Unity 2020.3.18f1 and 2020.3.35f1 to see if that helped. Not sure if this is something that has happened to others and if there's any solution. Thanks.

**Comment by micahpearlman** [comment]
Try using https instead of ssh: https://github.com/fsstudio-team/ZeroSimROSUnity.git

If https works, it is probably because you do not have ssh authentication setup for GitHub.

**Comment by vbelkina** [comment]
Hi, thanks for your reply. 
The https also did not work:
![image](https://user-images.githubusercontent.com/72238100/173406389-014bb6d7-9fb1-4c7a-97de-37f39a93fa20.png)

I have tried to import other packages, and I don't have any issues.

**Comment by micahpearlman** [comment]
@vbelkina  My apologies, it seems to have been an issue on our end.  Please try again.

**Comment by vbelkina** [comment]
It worked! Thank you for your help.

**Comment by vbelkina** [comment]
Hi, thanks for your reply!
The https also didn't work.
