### ISSUE TITLE
Unity 2020. add package from git url failed

### ISSUE THREAD

**Issue by CheAbdullah** [fsstudio-team/ZeroSimROSUnity#29]
[Package Manager Window] Cannot perform upm operation: Unable to add package [git@github.com:fsstudio-team/ZeroSimROSUnity.git]:
  Error when executing git command. Host key verification failed.
  fatal: Could not read from remote repository.

Select Add Package From Git URL... and enter git@github.com:fsstudio-team/ZeroSimROSUnity.git.
{https://github.com/fsstudio-team/ZeroSimROSUnity}

**Comment by anqitongxue** [comment]
这里是氨气同学的QQ邮箱，您的邮件我已收到，祝生活愉快~

**Comment by CheAbdullah** [comment]
[Package Manager Window] Cannot perform upm operation: Unable to add package [git@github.com:fsstudio-team/ZeroSimROSUnity.git]:
  Error when executing git command. git@github.com: Permission denied (publickey).
  fatal: Could not read from remote repository.

  Please make sure you have the correct access rights
  and the repository exists.

is this link working? git@github.com:fsstudio-team/ZeroSimROSUnity.git

**Comment by CheAbdullah** [comment]
DOWNLOAD THIS .JSON.
INSTALL FROM FILE##

https://raw.githubusercontent.com/fsstudio-team/ZeroSimROSUnity/master/package.json

**Comment by Rive4** [comment]
Hello,

I tried in both ways but I am still having problems to import it.
Using package.json file it appears in package manager that I installed the package, but it does not import anything.

EDIT:
Finally I could solve it by using the GIT https URL and it worked :)
